# Generated by Django 4.0.4 on 2022-08-14 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_post_profile_like_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='like_post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
