# Generated by Django 4.0.4 on 2022-08-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_post_profile_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='like_count',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
