# Generated by Django 3.2.13 on 2022-08-17 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QnA', '0001_initial'),
        ('account', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='main.Hashtag'),
        ),
        migrations.AddField(
            model_name='question',
            name='nickname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
        migrations.AddField(
            model_name='question',
            name='q_clip',
            field=models.ManyToManyField(blank=True, related_name='q_clip', to='account.Profile'),
        ),
        migrations.AddField(
            model_name='question',
            name='q_like',
            field=models.ManyToManyField(blank=True, related_name='q_likes', to='account.Profile'),
        ),
        migrations.AddField(
            model_name='question',
            name='q_user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q_user', to='account.profile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='a_parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QnA.answer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.profile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='qna_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='QnA.question'),
        ),
    ]
