# Generated by Django 4.0.4 on 2022-07-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qna',
            old_name='q_photo',
            new_name='image',
        ),
    ]
