# Generated by Django 4.1 on 2022-08-12 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("QnA", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="a_parent_comment",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="QnA.answer"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="create_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
