# Generated by Django 4.1 on 2022-08-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QnA", "0003_question_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="q_clicks",
            field=models.PositiveIntegerField(default=0, verbose_name="조회수"),
        ),
        migrations.AddField(
            model_name="question",
            name="q_likes",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
