# Generated by Django 3.2.13 on 2022-08-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0003_rename_name_answer_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='q_clips',
            new_name='q_clicks',
        ),
        migrations.AlterField(
            model_name='question',
            name='q_likes',
            field=models.PositiveIntegerField(default=0, verbose_name='추천수'),
        ),
    ]
