# Generated by Django 4.1 on 2022-08-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0003_rename_name_answer_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_likes',
            field=models.PositiveIntegerField(default=0, verbose_name='추천수'),
        ),
    ]
