# Generated by Django 4.1 on 2022-08-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QnA", "0004_question_q_clicks_question_q_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="text",
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.TextField(),
        ),
    ]
