# Generated by Django 4.1 on 2022-08-14 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_rename_created_at_r_comment_create_at_and_more"),
        ("free", "0003_remove_p_comment_pc_writer_p_comment_create_at_and_more"),
        ("QnA", "0002_answer_a_parent_comment_answer_create_at_answer_name"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hashtag",
            name="p_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="free.free"
            ),
        ),
        migrations.AddField(
            model_name="hashtag",
            name="qna_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="QnA.question",
            ),
        ),
        migrations.AddField(
            model_name="hashtag",
            name="r_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="review.review",
            ),
        ),
    ]
