# Generated by Django 4.1 on 2022-08-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_review_gather'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review_gather',
        ),
    ]
