# Generated by Django 3.2.13 on 2022-08-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='r_likes',
            field=models.PositiveIntegerField(default=0, verbose_name='추천수'),
        ),
    ]
