# Generated by Django 4.1 on 2022-08-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="r_comment",
            old_name="created_at",
            new_name="create_at",
        ),
        migrations.RenameField(
            model_name="r_comment",
            old_name="parent_comment",
            new_name="r_parent_comment",
        ),
        migrations.AlterModelTable(
            name="r_comment",
            table=None,
        ),
    ]
