# Generated by Django 4.1 on 2022-08-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_r_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='r_clips',
            new_name='r_clicks',
        ),
    ]
