# Generated by Django 4.1 on 2022-08-19 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_rename_r_clips_review_r_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_comment',
            name='r_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_comments', to='review.review'),
        ),
    ]
