# Generated by Django 4.0.4 on 2022-08-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_hashtag_blog_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='r_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
