# Generated by Django 4.0.4 on 2022-08-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0017_remove_blog_r_clicks_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
