# Generated by Django 4.0.6 on 2022-08-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0018_delete_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='r_likes',
        ),
        migrations.AddField(
            model_name='blog',
            name='r_clikes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
