# Generated by Django 4.0.6 on 2022-08-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0019_alter_blog_options_remove_blog_r_likes_blog_r_clikes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
    ]
