# Generated by Django 4.0.6 on 2022-08-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0020_alter_blog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='r_clikes',
            field=models.IntegerField(default=0),
        ),
    ]
