# Generated by Django 4.0.6 on 2022-08-08 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0022_bookmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
