# Generated by Django 4.0.4 on 2022-08-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0023_delete_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_hit', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='blog',
            name='r_clikes',
        ),
    ]
