# Generated by Django 4.0.4 on 2022-08-11 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0024_post_remove_blog_r_clikes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
