# Generated by Django 4.0.4 on 2022-08-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0025_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='r_clikes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
