# Generated by Django 4.0.4 on 2022-08-15 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0027_rename_r_clikes_blog_r_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='r_like',
            field=models.ManyToManyField(blank=True, related_name='r_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='r_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_Blog_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
