# Generated by Django 4.0.4 on 2022-08-16 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0032_remove_blog_r_comment_clicks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='r_comment',
            name='r_comment_clicks',
        ),
    ]
