# Generated by Django 3.2.13 on 2022-08-17 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('free', '0001_initial'),
        ('account', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='free',
            name='hashtags',
            field=models.ManyToManyField(blank=True, null=True, to='main.Hashtag'),
        ),
        migrations.AddField(
            model_name='free',
            name='nickname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
