# Generated by Django 4.0.6 on 2022-07-27 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='body',
            new_name='p_body',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='pub_date',
            new_name='p_date',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='p_title',
        ),
    ]
