# Generated by Django 4.1.2 on 2022-10-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('free', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='free',
            name='hashtags',
            field=models.ManyToManyField(blank=True, null=True, to='main.hashtag'),
        ),
    ]
