# Generated by Django 4.0.6 on 2022-07-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0002_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
