# Generated by Django 4.1 on 2022-08-12 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("free", "0002_delete_hashtag_alter_free_hashtags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="p_comment",
            name="pc_writer",
        ),
        migrations.AddField(
            model_name="p_comment",
            name="create_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="p_comment",
            name="name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="p_comment",
            name="p_parent_comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="free.p_comment",
            ),
        ),
    ]
