# Generated by Django 4.1 on 2022-08-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0003_auto_20220818_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_like',
            name='p_likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
