# Generated by Django 4.0.4 on 2022-08-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0003_remove_p_comment_pc_writer_p_comment_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free',
            name='p_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
