# Generated by Django 4.0.6 on 2022-07-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0003_alter_blog_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
