# Generated by Django 4.1 on 2022-08-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0004_alter_free_like_p_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_like',
            name='p_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
