# Generated by Django 3.2.13 on 2022-08-19 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0004_free_p_clicks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Free_Clip',
        ),
    ]
