# Generated by Django 3.2.13 on 2022-08-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0005_delete_free_clip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_like',
            name='p_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
