# Generated by Django 4.1 on 2022-08-18 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('free', '0005_alter_free_like_p_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Free_Clicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_clicks', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('p_clip', models.ManyToManyField(blank=True, related_name='p_clip', to='account.profile')),
                ('p_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='free.free')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Free_Clip',
        ),
    ]
