# Generated by Django 4.1 on 2022-08-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0006_free_clicks_delete_free_clip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='free_clicks',
            name='p_clicks',
        ),
        migrations.AddField(
            model_name='free',
            name='p_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
