# Generated by Django 4.1 on 2022-08-19 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0007_remove_free_clicks_p_clicks_free_p_clicks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Free_Clicks',
        ),
    ]
