# Generated by Django 4.0.6 on 2022-07-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0007_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hashtags',
            field=models.ManyToManyField(blank=True, null=True, to='free.hashtag'),
        ),
    ]
