# Generated by Django 4.0.6 on 2022-07-28 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0008_blog_hashtags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='p_comment',
        ),
    ]
