# Generated by Django 4.0.6 on 2022-07-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0009_rename_comment_p_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='p_likes',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
