# Generated by Django 4.0.4 on 2022-08-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0010_blog_p_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='p_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
