# Generated by Django 4.0.6 on 2022-08-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0011_alter_blog_p_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='p_clicks',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
