# Generated by Django 4.0.4 on 2022-08-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0012_alter_blog_p_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='p_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
