# Generated by Django 4.0.4 on 2022-08-13 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0013_alter_blog_p_clicks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='minji_Blog',
        ),
    ]
