# Generated by Django 4.0.4 on 2022-08-13 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0014_rename_blog_minji_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='minji_Blog',
            new_name='Blog',
        ),
    ]
