# Generated by Django 4.0.4 on 2022-08-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0015_rename_minji_blog_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='p_likes',
        ),
    ]
