# Generated by Django 4.0.4 on 2022-08-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0017_blog_like_users_blog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='like_users',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
    ]
