# Generated by Django 4.0.4 on 2022-08-14 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('free', '0019_blog_like_blog_like_count_blog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='like',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='like_count',
        ),
        migrations.AddField(
            model_name='blog',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_blog', to=settings.AUTH_USER_MODEL),
        ),
    ]
