# Generated by Django 4.0.4 on 2022-08-14 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0020_remove_blog_like_remove_blog_like_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='like_users',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
    ]
