# Generated by Django 4.0.4 on 2022-08-15 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('free', '0022_blog_like_blog_like_count_blog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='like',
            new_name='f_like',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='like_count',
            new_name='f_likes',
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='f_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
