# Generated by Django 4.0.4 on 2022-08-16 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0024_p_comment_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_comment',
            name='comments',
        ),
    ]
